#!/bin/sh

FULL_INSTALL=1

install_ROS_Kinetic(){
# setup source list
echo "setting up source list"
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'

# install keys
echo "installing keys"
sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116

#install ROS
echo "installing ROS"
echo "FULL_install is $FULL_INSTALL"

sudo apt-get update

if [ $FULL_INSTALL = 1 ];then
	echo "installing dektop-full version"
	sudo apt-get install ros-kinetic-desktop-full

else
	echo "installing dektop version"
	sudo apt-get install ros-kinetic-desktop

fi

# initialize rosdep
echo "initialize rosdep"
sudo rosdep init
rosdep update


#source ROS in bash and zsh
echo "sourcing ROS in bash and zsh"

echo "source /opt/ros/kinetic/setup.bash" >> ~/.bashrc
source ~/.bashrc

echo "source /opt/ros/kinetic/setup.zsh" >> ~/.zshrc
source ~/.zshrc

# installing dependencies
echo "installing dependencies"
sudo apt-get install python-rosinstall python-rosinstall-generator python-wstool build-essential

}


install_ROS_Kinetic

